### ISSUE TITLE
Detection of multiple inputs

### ISSUE THREAD

**Issue by TylorB** [charlescao460/SerialKeyboardMouseController#1]
The AC can detect multiple mouse inputs and flag it for being suspicions, a USB host shield should be added to the Arduino and passed through to computer #1 with the game so there is only one mouse input. This creates the issue of combining the two mouse inputs, real mouse inputs should be modified via data from serial connection move the cursor to a certain position. With passthrough and input combining alongside proper hid descriptor spoofing there would be no detection vectors.

**Comment by charlescao460** [comment]
Hi, Thank you for the suggestions. 

This little project was designed to provide an easy-to-made, software-controlled hardware USB HID mouse & keyboard. So, no "real" input is needed or required. All the mouse/keyboard movement was provided by serial, and therefore combining mouse signals was not my original use case. If you're trying to implement some macros for FPS, that's completely a different use case. 

Also, in my setup, our Arduino board is the only HID device connected to the target (computer#1), so there is only one mouse presented in the system. And computer#1 is completely free of any suspicious software or driver.

Speaking about detection, if you look closely at the [USB-IF's document](https://www.usb.org/sites/default/files/hid1_11.pdf), our HID packets and descriptors look normal as the real mouse/keyboard. Therefore, I couldn't see any significant meaning of using a real mouse's input as a baseline. 

The only suspicious thing is that our mouse uses absolute coordination rather than relative coordination, but that's for precise coordinate-based control with computer vision (CV) involved. Since absolute coordination is supported in USB HID standard, there's no reason for AC to ban an absolute mouse.
